-- ************************************************************
-- Sequel Pro SQL dump
-- Version 4541
--
-- http://www.sequelpro.com/
-- https://github.com/sequelpro/sequelpro
--
-- Host: 192.168.10.10 (MySQL 5.7.12-0ubuntu1.1)
-- Database: chat
-- Generation Time: 2016-11-07 16:42:08 +0000
-- ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Dump of table chats
-- ------------------------------------------------------------

DROP TABLE IF EXISTS chats;

CREATE SEQUENCE chats_seq;

CREATE TABLE chats (
  id int check (id > 0) NOT NULL DEFAULT NEXTVAL ('chats_seq'),
  user_id int DEFAULT NULL,
  ip varchar(200) DEFAULT NULL,
  user_agent varchar(200),
  email varchar(200) DEFAULT NULL,
  messages varchar(200),
  PRIMARY KEY (id)
) ;


INSERT INTO chats (id, user_id, ip, user_agent, email, messages)
VALUES
  (1,1,NULL,NULL,NULL,'blah'),
  (2,23,NULL,NULL,NULL,NULL),
  (3,NULL,NULL,NULL,NULL,'blah'),
  (4,23,NULL,NULL,NULL,NULL),
  (5,NULL,NULL,NULL,NULL,'blah'),
  (6,23,NULL,NULL,NULL,NULL),
  (7,NULL,NULL,NULL,NULL,'blah'),
  (8,23,NULL,NULL,NULL,NULL),
  (9,NULL,NULL,NULL,NULL,'blah'),
  (10,23,NULL,NULL,NULL,NULL),
  (11,NULL,NULL,NULL,NULL,'blah'),
  (12,23,NULL,NULL,NULL,NULL);



-- Dump of table users
-- ------------------------------------------------------------

DROP TABLE IF EXISTS users;

CREATE SEQUENCE users_seq;

CREATE TABLE users (
  id int check (id > 0) NOT NULL DEFAULT NEXTVAL ('users_seq'),
  name varchar(11) DEFAULT NULL,
  PRIMARY KEY (id)
) ;


INSERT INTO users (id, name)
VALUES
  (1,'Bob');
